[versions]
kotlin = "2.2.21"

[plugins]
kotlin-jvm      = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
bom-junit5      = { module = "org.junit:junit-bom", version = "5.10.0" }

junit-jupiter   = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher  = { module = "org.junit.platform:junit-platform-launcher" }
assertj         = { module = "org.assertj:assertj-core", version = "3.27.6" }
